-- Add migration script here
ALTER TYPE VERIFICATION_LEVEL RENAME VALUE 'AutoVerified' TO 'Auto';
ALTER TYPE VERIFICATION_LEVEL RENAME VALUE 'ManualVerified' TO 'Manual';
ALTER TYPE VERIFICATION_LEVEL RENAME VALUE 'PolyTechCore' TO 'Core';
